baseurl = "https://fabrizioregal.li"
title = "Fabrizio Regalli"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#disqusShortname = "fabrizioregal-li"


[markup.highlight]
style = "github-dark"

[params]
  author = "Fabrizio Regalli"
  #info = "Full Stack DevOps and Magician"
  info = "Opensource, DevOps and Cloud Enthusiast"
  description = "Fabrizio Regalli's personal website"
  keywords = "blog,developer,personal,fabrizio regalli"
  #avatarurl = "images/avatar.jpg"
  gravatar = "fabreg@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2004

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]


  [params.shareButtons]
  networks = [ "facebook", "twitter", "email", "linkedin", ]
  size = "medium"         # small,medium,large
  icon = "solid"          # solid,solidcircle
  buttonMargin = "0.2em"


[params.giscus] # https://giscus.app
  repo = "fabreg/fabreg.github.io"
  repoID = "R_kgDOLcn56A"
  category = "General"
  categoryID = "DIC_kwDOLcn56M4Cdymb"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "dark"
  lang = "en"
  loading = ""

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/fabrizioregalli/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/fabreg/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/fabreg/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/riztwi/"
[[params.social]]
  name = "Strava"
  icon = "fa-brands fa-strava fa-2x"
  weight = 4
  url = "https://www.strava.com/athletes/25687938"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Contact Me"
  weight = 3
  url = "contacts/"

[services]
  [services.googleAnalytics]
    ID = 'G-5QR7HRX1V3'
